### ISSUE TITLE
TERM variable set to dtterm causing warning

### ISSUE THREAD

**Issue by gondarlinux** [dcantrell/cderpm#8]
Dave, awesome work you've done here!  I just installed the RPM from your COPR repo and I am so pleased.  Having played with the env for a bit, I notice the following behaviour:

[root@localhost ~]# less /var/log/messages                                                
WARNING: terminal is not fully functional
/var/log/messages  (press RETURN)
...

After looking at the TERM variable:

[root@localhost ~]# echo $TERM
dtterm

... and some google searching, I figured that the TERM variable should be xterm or vt100 or some such.  But, I can't find where this variable is being set?  I thought /usr/dt/bin/Xsession, but no dice.  

Any ideas on where this is getting set?

Thanks,
 Michael G

**Comment by jtrulson** [comment]
Try:

`sudo tic /usr/dt/config/dtterm.ti`

This will add the dtterm definition to your terminfo database.

**Comment by gondarlinux** [comment]
WINNER!!!!!!

Thank you Jon!  You learn something new every day.
